[package]
name = "shtcx"
version = "0.1.0"
edition = "2018"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
documentation = "https://docs.rs/shtcx"
repository = "https://github.com/dbrgn/shtcx-rs"
license = "MIT OR Apache-2.0"
description = "Platform agnostic Rust driver for the Sensirion SHTCx series temperature/humidity sensors."
readme = "README.md"
keywords = ["shtcx", "sensirion", "temperature", "humidity", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[features]
default = []
# Sensors
shtc1 = []
shtc3 = []
shtw2 = []
# Generic fallback
generic = []

[dependencies]
embedded-hal = "0.2"

[dev-dependencies]
embedded-hal-mock = "0.7.1"
linux-embedded-hal = "0.3"
termion = "1.5"
tui = "0.8"

[profile.release]
lto = true
