name: CI
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  ensure_no_std:
    name: Ensure no_std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Download cargo-nono
        run: |
          wget https://github.com/hobofan/cargo-nono/releases/download/0.1.6/cargo-nono-0.1.6-x86_64-unknown-linux-gnu.tar.gz \
            && tar xfvz cargo-nono-0.1.6-x86_64-unknown-linux-gnu.tar.gz
      - name: Run check
        run: ./cargo-nono check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - run: cargo fmt -- --check
